version: '3'
services:
  unibarrage:
    image: timexingjian/unibarrage:latest
    # 本地构建取消注释
    # pull_policy: never
    container_name: unibarrage
    ports:
      - "8080:8080"
      - "7777:7777"
    volumes:
      - ./data:/app/data
    restart: always
