version: '3'
services:
  unibarrage:
    image: timexingjian/unibarrage:latest
    pull_policy: never
    ports:
      - "8080:8080"
      - "7777:7777"
    volumes:
      - ./data:/app/data
    restart: always
